Time kmer calculation: 0.000003 s
Kmer table, number of sequence names: 112902
Kmer table, number of sequences: 112902
Kmer table, number of words: 1024
Time kmer reading: 85.328056 s
___________________
Queue length: 1
 Turn 0 with 112902 sequences
   Ratio of explicative variable: 1.000000
   Distance time: 4397.734187 s
   Number of composantes: 1024 s
   Number of sequences: 112902 s
   Cluster time: 683.998209 s
   Mate pair values: 0.951698 and 0.999155
___________________
Queue length: 2
 Turn 1 with 106582 sequences
   Ratio of explicative variable: 1.000000
   Distance time: 4547.160787 s
   Number of composantes: 1024 s
   Number of sequences: 106582 s
   Cluster time: 640.480428 s
   Mate pair values: 0.940097 and 0.991169
___________________
Queue length: 3
Traceback (most recent call last):
  File "../../script/classification.py", line 641, in <module>
    verbose)
  File "../../script/classification.py", line 71, in classification
    pca, expl_var_ratio = compute_pca(kmer_table[kmer_indice])
  File "../../script/classification.py", line 334, in compute_pca
    pca.fit(kmer_table)
  File "/usr/local/lib/python3.4/dist-packages/sklearn/decomposition/pca.py", line 329, in fit
    self._fit(X)
  File "/usr/local/lib/python3.4/dist-packages/sklearn/decomposition/pca.py", line 392, in _fit
    return self._fit_full(X, n_components)
  File "/usr/local/lib/python3.4/dist-packages/sklearn/decomposition/pca.py", line 416, in _fit_full
    U, S, V = linalg.svd(X, full_matrices=False)
  File "/usr/local/lib/python3.4/dist-packages/scipy/linalg/decomp_svd.py", line 132, in svd
    raise LinAlgError("SVD did not converge")
numpy.linalg.linalg.LinAlgError: SVD did not converge
